services:
  app-db:
    image: postgres:17
    container_name: app-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: app-db
      POSTGRES_PASSWORD: postgres
    volumes:
      - app-db-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.5
    container_name: keycloak
    depends_on:
      - keycloak-db
    ports:
      - "8080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_FEATURES: update-email
    command: start-dev
    networks:
      - keycloak-net

  keycloak-db:
    image: postgres:17
    container_name: keycloak-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_DB: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    networks:
      - keycloak-net

volumes:
  app-db-data:
  keycloak-db-data:

networks:
  keycloak-net:
