server:
  port: 8081
spring:
  application:
    name: keycloak-poc
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:app-db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  flyway:
    enabled: false
    validate-migration-naming: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.server-url}/realms/${keycloak.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
keycloak:
  server-url: http://localhost:8080
  realm: keycloak-poc
  client-id: keycloak-poc
  client-secret: sjIsDWduBz9Smgppc4m7KNmfbPJEaOl0
logging:
  level:
    root: INFO
    io.github.nayetdet: DEBUG
